openapi: 3.0.1
info:
  title: Patient
  version: 0.1.0
servers:
- url: "{server}:{port}/patient"
  variables:
    server:
      default: http://localhost
    port:
      default: servicePort
paths:
  /{patientId}/summary:
    get:
      summary: Resource to get patient summary as FHIR IPS bundle
      operationId: getPatientidSummary
      parameters:
      - name: patientId
        in: path
        description: ID of the patient
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
